notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.net#concerto"
    use_notice: true
    skip_join: true

language: php

php:
  - 5.4
  - 5.5
  - 5.6

install: ./scripts/travis-install.sh

before_script:
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-text